### ISSUE TITLE
Ékezetes karakterek

### ISSUE THREAD

**Issue by martonkrisztian** [akosk/WorktimeRegister#45]
A nevekben nem volt ékezetes karakter? Pl. Marton Krisztian nevében nincs, de Illés Sándor esetében van.

**Comment by akosk** [comment]
A felhasználó nevét az LDAP-ból importáljuk az első bejelentkezéskor. Emr1 és emr2 nevében nincs ékezet, a többit nem tudom tesztelni, de mivel Illés Sándor ékezetes, ezért azt valószínűsítem, hogy az LDAP-ben van így megadva.

**Comment by martonkrisztian** [comment]
Az ügye járható út lenne, hogy a nevet ne az LDAP-ból vegye, hanem az adószám megadása után a bérügy adatbázisából?

**Comment by akosk** [comment]
Semmi akadálya.
