### ISSUE TITLE
Távollétek zárolva állapotban elérhető funkciók

### ISSUE THREAD

**Issue by martonkrisztian** [akosk/WorktimeRegister#48]
Zárolva lett adott hónapban a jelenlét. Visszamenőleg nem lehet távollétet megadni, azonban 20-a (16) utánra lehessen megadni. Ezt magamnak is felírtam, még gondolkodok a napon (adott hónap 16, vagy 20, vagy más?).

**Comment by akosk** [comment]
Tehát:
* Távollétet múltbeli időpontra ne lehessen megadni.
* Jelenlétek zárolása után távollétet 20-a (vagy 16-a) és az előtti időpontra ne lehessen megadni.

Ez így ok?

**Comment by martonkrisztian** [comment]
Távollét zárolása:
- távollétet csak adott hónap 16-án, vagy utána lehessen zárolni, az adott szervezeti egységbe tartozó felhasználók munkaidő nyilvántartásának töltöttségét nem kell ellenőrizni
Távollét zárolva lett:
- ekkor a zárolást megelőző nappal bezárólag ne lehessen távollétet se hozzáadni, se törölni (érkezést, távozást lehessen még megadni)
