### ISSUE TITLE
Rendes szabadság megadása probléma

### ISSUE THREAD

**Issue by martonkrisztian** [akosk/WorktimeRegister#68]
2015. január végén Illés Sanyi és én is (emr2 userrel) próbáltunk Sanyinak megadni rendes szabadságot 2015.január 22-re. Jan. 23-ra megtudta adni, de jan 22-re nem. Végül is az adatbázisba beszúrtam kézzel egy sort.
Gondolom ez az előző napi zárolás miatt van, ügye?

**Comment by akosk** [comment]
Igen. Attól a naptól fogva, hogy zároltál, nem lehet a távolléteket megadni.

**Comment by akosk** [comment]
#48 foglalkozott ezzel a kérdéssel.

**Comment by martonkrisztian** [comment]
Távollétek zárolása után, tárgy hóban, a zárolás időpontjától korábbi időpontra nem szabad tudni megadni már távollétet, de a zárolást követő időpontra szabad. 
Tehát, ha január 21-én zároltak távollétet, akkor január 1-20 közötti időszakra vonatkozóan nem szabad már változtatni, de január 21-31 közötti időszakra vonatkozóan lehet, akár távollétet is megadni, a jelenlét zárolásáig. Ez utóbbit pl. feb. 4-én teszik meg.
