### ISSUE TITLE
Importálás logikája

### ISSUE THREAD

**Issue by martonkrisztian** [akosk/WorktimeRegister#76]
Ha valaki mondjuk XY a bér és munkaügyi rendszerből kikerül, mert elment az egyetemről. A munkaidő nyilvántartóban viszont szerepel. Mi azt a listát importáljuk a munkaidő nyilvántartóba, amelyben XY már nem szerepel. Ettől függetlenül a munkaidő nyilvántartóból nem fog kikerülni?
Ténylegesen nem is lenne jó, ha kikerülne, mert pl. 3 hónappal ezelőtt még szerepelt. De ettől a hónaptól már inaktív kellene, hogy legyen.

**Comment by akosk** [comment]
Jelenleg nem kerül ki, mert importálásnál egyszerűen csak üríti a korábbi import adatokat, és újra elvégzi a szervezeti egység, stb. beállításokat, de csak azokra a userekre, akik benne vannak az újonnan importált táblában, tehát a törölt felhasználók tovább élnek a rendszerben a korábbi jogosítványaikkal.
Az inaktívvá állítás szerintem is megoldja ezt a problémát.
