### ISSUE TITLE
Importálás logikája. A vezető kérdés.

### ISSUE THREAD

**Issue by martonkrisztian** [akosk/WorktimeRegister#77]
Ha valakinek vezetői "jog" lett beállítva kézzel, akkor ezt importáláskor nem kellene, hogy felülírja a rendszer.

**Comment by akosk** [comment]
Tehát ha valakinek manuálisan lett a szerepköre beállítva, annak onnantól nem kell, hogy figyelembe vegye azt ami az importból jön?

**Comment by martonkrisztian** [comment]
Igen. Sőt, annyi is elég lenne az importnál, hogy: 
egyszerűen vezetői jogot, csak adhat a rendszer import során el nem vehet.

És ez életszerű, mert nagyon ritkán vesznek el jogot valakitől. Ezt kézzel lehet állítani.
